BulkySh.Web/Areas/Admin/Controllers/OrderController.cs
using BulkySh.Models.ViewModels;
using BulkySh.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe.Checkout;
using Stripe;
using System.Security.Claims;

namespace BulkySh.Web.Areas.Admin.Controllers
{
	[Area("admin")]
	[Authorize]
	public class OrderController : Controller
	{


		private readonly IUnitOfWork _unitOfWork;
		[BindProperty]
		public OrderVM OrderVM { get; set; }
		public OrderController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Details(int orderId)
		{
			OrderVM = new()
			{
				OrderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == orderId, includeProperties: "ApplicationUser"),
				OrderDetail = _unitOfWork.OrderDetail.GetAll(u => u.OrderHeaderId == orderId, includeProperties: "Product")
			};

			return View(OrderVM);
		}
		[HttpPost]
		[Authorize(Roles = SD.Roles.Admin + "," + SD.Roles.Admin)]
		public IActionResult UpdateOrderDetail()
		{
			var orderHeaderFromDb = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);
			orderHeaderFromDb.Name = OrderVM.OrderHeader.Name;
			orderHeaderFromDb.PhoneNumber = OrderVM.OrderHeader.PhoneNumber;
			orderHeaderFromDb.StreetAddress = OrderVM.OrderHeader.StreetAddress;
			orderHeaderFromDb.City = OrderVM.OrderHeader.City;
			orderHeaderFromDb.State = OrderVM.OrderHeader.State;
			orderHeaderFromDb.PostalCode = OrderVM.OrderHeader.PostalCode;
			if (!string.IsNullOrEmpty(OrderVM.OrderHeader.Carrier))
			{
				orderHeaderFromDb.Carrier = OrderVM.OrderHeader.Carrier;
			}
			if (!string.IsNullOrEmpty(OrderVM.OrderHeader.TrackingNumber))
			{
				orderHeaderFromDb.Carrier = OrderVM.OrderHeader.TrackingNumber;
			}
			_unitOfWork.OrderHeader.Update(orderHeaderFromDb);
			_unitOfWork.Save();

			TempData["Success"] = "Order Details Updated Successfully.";


			return RedirectToAction(nameof(Details), new { orderId = orderHeaderFromDb.Id });
		}


		[HttpPost]
		[Authorize(Roles = SD.Roles.Admin + "," + SD.Roles.Admin)]
		public IActionResult StartProcessing()
		{
			_unitOfWork.OrderHeader.UpdateStatus(OrderVM.OrderHeader.Id, SD.Status.InProcess);
			_unitOfWork.Save();
			TempData["Success"] = "Order Details Updated Successfully.";
			return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
		}

		//[HttpPost]
		//[Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
		//public IActionResult ShipOrder()
		//{

		//	var orderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);
		//	orderHeader.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;
		//	orderHeader.Carrier = OrderVM.OrderHeader.Carrier;
		//	orderHeader.OrderStatus = SD.Status.Shipped;
		//	orderHeader.ShippingDate = DateTime.Now;
		//	if (orderHeader.PaymentStatus == SD.PaymentStatus.DelayedPayment)
		//	{
		//		orderHeader.PaymentDueDate = DateTime.Now.AddDays(30);
		//	}

		//	_unitOfWork.OrderHeader.Update(orderHeader);
		//	_unitOfWork.Save();
		//	TempData["Success"] = "Order Shipped Successfully.";
		//	return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
		//}


		[HttpPost]
		[Authorize(Roles = SD.Roles.Admin + "," + SD.Roles.Admin)]
		public IActionResult CancelOrder()
		{

			var orderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);

			if (orderHeader.PaymentStatus == SD.PaymentStatus.Approved)
			{
				var options = new RefundCreateOptions
				{
					Reason = RefundReasons.RequestedByCustomer,
					PaymentIntent = orderHeader.PaymentIntentId
				};

				var service = new RefundService();
				Refund refund = service.Create(options);

				_unitOfWork.OrderHeader.UpdateStatus(orderHeader.Id, SD.Status.Cancelled, SD.Status.Refunded);
			}
			else
			{
				_unitOfWork.OrderHeader.UpdateStatus(orderHeader.Id, SD.Status.Cancelled, SD.Status.Cancelled);
			}
			_unitOfWork.Save();
			TempData["Success"] = "Order Cancelled Successfully.";
			return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });

		}



		[ActionName("Details")]
		[HttpPost]
		public IActionResult Details_PAY_NOW()
		{
			OrderVM.OrderHeader = _unitOfWork.OrderHeader
				.Get(u => u.Id == OrderVM.OrderHeader.Id, includeProperties: "ApplicationUser");
			OrderVM.OrderDetail = _unitOfWork.OrderDetail
				.GetAll(u => u.OrderHeaderId == OrderVM.OrderHeader.Id, includeProperties: "Product");

			//stripe logic
			var domain = Request.Scheme + "://" + Request.Host.Value + "/";
			var options = new SessionCreateOptions
			{
				SuccessUrl = domain + $"admin/order/PaymentConfirmation?orderHeaderId={OrderVM.OrderHeader.Id}",
				CancelUrl = domain + $"admin/order/details?orderId={OrderVM.OrderHeader.Id}",
				LineItems = new List<SessionLineItemOptions>(),
				Mode = "payment",
			};

			foreach (var item in OrderVM.OrderDetail)
			{
				var sessionLineItem = new SessionLineItemOptions
				{
					PriceData = new SessionLineItemPriceDataOptions
					{
						UnitAmount = (long)(item.Price * 100), // $20.50 => 2050
						Currency = "usd",
						ProductData = new SessionLineItemPriceDataProductDataOptions
						{
							Name = item.Product.Title
						}
					},
					Quantity = item.Count
				};
				options.LineItems.Add(sessionLineItem);
			}


			var service = new SessionService();
			Session session = service.Create(options);
			_unitOfWork.OrderHeader.UpdateStripePaymentID(OrderVM.OrderHeader.Id, session.Id, session.PaymentIntentId);
			_unitOfWork.Save();
			Response.Headers.Add("Location", session.Url);
			return new StatusCodeResult(303);
		}

		public IActionResult PaymentConfirmation(int orderHeaderId)
		{

			OrderHeader orderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == orderHeaderId);
			if (orderHeader.PaymentStatus == SD.PaymentStatus.DelayedPayment)
			{
				//this is an order by company

				var service = new SessionService();
				Session session = service.Get(orderHeader.SessionId);

				if (session.PaymentStatus.ToLower() == "paid")
				{
					_unitOfWork.OrderHeader.UpdateStripePaymentID(orderHeaderId, session.Id, session.PaymentIntentId);
					_unitOfWork.OrderHeader.UpdateStatus(orderHeaderId, orderHeader.OrderStatus, SD.PaymentStatus.Approved);
					_unitOfWork.Save();
				}


			}


			return View(orderHeaderId);
		}



		#region API CALLS

		[HttpGet]
		public IActionResult GetAll(string status)
		{
			IEnumerable<OrderHeader> objOrderHeaders;


			if (User.IsInRole(SD.Roles.Admin) || User.IsInRole(SD.Roles.Admin))
			{
				objOrderHeaders = _unitOfWork.OrderHeader.GetAll(includeProperties: "ApplicationUser").ToList();
			}
			else
			{

				var claimsIdentity = (ClaimsIdentity)User.Identity;
				var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

				objOrderHeaders = _unitOfWork.OrderHeader
					.GetAll(u => u.ApplicationUserId == userId, includeProperties: "ApplicationUser");
			}


			switch (status)
			{
				case "pending":
					objOrderHeaders = objOrderHeaders.Where(u => u.PaymentStatus == SD.PaymentStatus.DelayedPayment);
					break;
				case "inprocess":
					objOrderHeaders = objOrderHeaders.Where(u => u.OrderStatus == SD.Status.InProcess);
					break;
				case "completed":
					objOrderHeaders = objOrderHeaders.Where(u => u.OrderStatus == SD.Status.Shipped);
					break;
				case "approved":
					objOrderHeaders = objOrderHeaders.Where(u => u.OrderStatus == SD.Status.Approved);
					break;
				default:
					break;

			}


			return Json(new { data = objOrderHeaders });
		}


		#endregion
	}
}

BulkySh.Web/Areas/Admin/Controllers/UserController.cs
using BulkySh.DataAccess.Data;
using BulkySh.DataAccess.Repository;
using BulkySh.DataAccess.Repository.IRepository;
using BulkySh.Models.Models;
using BulkySh.Models.ViewModels;
using BulkySh.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Linq;
using static BulkySh.Utility.SD;

namespace BulkyShWeb.Areas.Admin.Controllers
{
	[Area("Admin")]
	//[Authorize(Roles = SD.Roles.Admin)]

	public class UserController : Controller
	{


		private readonly ApplicationDbContext _db;
		private readonly IUnitOfWork _unitOfWork;
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly RoleManager<ApplicationUser> _roleManager;




		public UserController(ApplicationDbContext db, IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager, RoleManager<ApplicationUser> roleManager)
		{
			_db = db;
			_unitOfWork = unitOfWork;
			_userManager = userManager;
			_roleManager = roleManager;
		}

		public IActionResult Index()
		{
			return View();
		}


		public IActionResult RoleManagment(string? userID)
		{	
			var roleId = _db.UserRoles.FirstOrDefault(ur=>ur.UserId == userID).RoleId;

			RoleManagmentVM roleVM = new RoleManagmentVM()
			{
				ApplicationUser = _db.ApplicationUsers.Include(u=>u.Company).FirstOrDefault(u => u.Id == userID),
				RoleList = _db.Roles.Select(i => new SelectListItem {
				Value = i.Id,
				Text = i.Name
				}),
				CompanyList = _db.Companies.Select(i => new SelectListItem
				{
					Value = i.Id.ToString(),
					Text = i.Name
				})
			};

			roleVM.ApplicationUser.Role = _db.Roles.FirstOrDefault(ur => ur.Id == roleId).Name;

			return View(roleVM);
		}

		[HttpPost]
		public IActionResult RoleManagment(RoleManagmentVM roleManagmentVM)
		{

			string oldRole = _userManager.GetRolesAsync(_unitOfWork.ApplicationUser.Get(u => u.Id == roleManagmentVM.ApplicationUser.Id))
					.GetAwaiter().GetResult().FirstOrDefault();

			ApplicationUser applicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == roleManagmentVM.ApplicationUser.Id);


			if (!(roleManagmentVM.ApplicationUser.Role == oldRole))
			{
				//a role was updated
				if (roleManagmentVM.ApplicationUser.Role == SD.Roles.Company)
				{
					applicationUser.CompanyId = roleManagmentVM.ApplicationUser.CompanyId;
				}
				if (oldRole == SD.Roles.Company)
				{
					applicationUser.CompanyId = null;
				}
				_unitOfWork.ApplicationUser.Update(applicationUser);
				_unitOfWork.Save();

				_userManager.RemoveFromRoleAsync(applicationUser, oldRole).GetAwaiter().GetResult();
				_userManager.AddToRoleAsync(applicationUser, roleManagmentVM.ApplicationUser.Role).GetAwaiter().GetResult();

			}
			else
			{
				if (oldRole == SD.Roles.Company && applicationUser.CompanyId != roleManagmentVM.ApplicationUser.CompanyId)
				{
					applicationUser.CompanyId = roleManagmentVM.ApplicationUser.CompanyId;
					_unitOfWork.ApplicationUser.Update(applicationUser);
					_unitOfWork.Save();
				}
			}

			return RedirectToAction("Index");
		}

		///////////////////////////////////////////////////////////////////


		//[HttpPost]
		//public IActionResult RoleManagment(RoleManagmentVM roleManagmentVM)
		//{
		//	Test(roleManagmentVM);
		//	try
		//	{
		//		string RoleID = _db.UserRoles.FirstOrDefault(u => u.UserId == roleManagmentVM.ApplicationUser.Id).RoleId;

		//		string oldRole = _db.Roles.FirstOrDefault(u => u.Id == RoleID).Id;

		//		if (!(roleManagmentVM.ApplicationUser.Role == oldRole))
		//		{
		//			ApplicationUser applicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == roleManagmentVM.ApplicationUser.Id);

		//			//a role was updated
		//			if (roleManagmentVM.ApplicationUser.Role == SD.Roles.Company)
		//			{
		//				applicationUser.CompanyId = roleManagmentVM.ApplicationUser.CompanyId;
		//			}
		//			if (oldRole == SD.Roles.Company)
		//			{
		//				applicationUser.CompanyId = null;
		//			}
		//			_unitOfWork.ApplicationUser.Update(applicationUser);
		//			_unitOfWork.Save();

		//			_userManager.RemoveFromRoleAsync(applicationUser, oldRole).GetAwaiter().GetResult();
		//			_userManager.AddToRoleAsync(applicationUser, roleManagmentVM.ApplicationUser.Role).GetAwaiter().GetResult();

		//		}
		//	}
		//	catch (Exception ex)
		//	{
		//		string message = ex.Message;
		//		if (ex.InnerException != null)
		//		{
		//			string details = ex.InnerException.ToString();
		//		}
		//	}




		//	return RedirectToAction("Index");
		//}


		//private void Test(RoleManagmentVM roleManagmentVM) 
		//{
		//	string RoleID = _db.UserRoles.FirstOrDefault(u => u.UserId == roleManagmentVM.ApplicationUser.Id).RoleId;

		//	string oldRole = _userManager.GetRolesAsync(_unitOfWork.ApplicationUser.Get(u=>u.Id== roleManagmentVM.ApplicationUser.Id)).GetAwaiter().GetResult().FirstOrDefault();




		//}


		#region API CALLS

		[HttpGet]
		public IActionResult GetAll()
		{
			List<ApplicationUser> objUserList = _db.ApplicationUsers.Include(u => u.Company).ToList();
			
			var userRoles = _db.UserRoles.ToList();
			
			var roles = _db.Roles.ToList();

			foreach (var user in objUserList) 
			{
				var roleID = userRoles.FirstOrDefault(r => r.UserId == user.Id).RoleId;
				
				user.Role = roles.FirstOrDefault(rn => rn.Id == roleID).Name;

				if (user.Company == null)
				{
					user.Company = new Company() { Name = "" };
				}
			}

			return Json(new { data = objUserList });
		}

		[HttpPost]
		public IActionResult LockUnlock([FromBody] string ID)
		{
			var objFromDb = _db.ApplicationUsers.FirstOrDefault(u => u.Id == ID);

			if (objFromDb == null)
			{
				return Json(new { success = false, Message = "Error while Locking/Unlocking" });
			}

			string status;
			if (objFromDb.LockoutEnd != null && objFromDb.LockoutEnd > DateTime.Now)
			{
				objFromDb.LockoutEnd = DateTime.Now;
				status = "Locked Successful";
			}
			else
			{
				objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
				status = "Unlocked Successful";
			}

			_db.SaveChanges();
			//return Json(new { success = true, Message = $"{status} Successful" });
			return Json(new { success = true, Message = status });
		}

		#endregion
	}
}

BulkySh.Web/ViewComponents/ShoppingCartViewComponent.cs
using BulkySh.Utility;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BulkySh.Web.ViewComponents
{
	public class ShoppingCartViewComponent : ViewComponent
	{
		private readonly IUnitOfWork _unitOfWork;
		public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}
		
		public async Task<IViewComponentResult> InvokeAsync()
		{
			var cliamdIdentity = (ClaimsIdentity)User.Identity;
			var cliam = cliamdIdentity.FindFirst(ClaimTypes.NameIdentifier);
			if (cliam != null)
			{
				if (HttpContext.Session.GetInt32(SD.SessionCart) != null)
				{
					HttpContext.Session.SetInt32(SD.SessionCart, _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == cliam.Value).Count());
				}
				return View(HttpContext.Session.GetInt32(SD.SessionCart));
			}
			else
			{
				HttpContext.Session.Clear();
				return View(0);
			}
		}
	}
}

BulkySh.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyShWeb</title>
    @*     <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap_sandstone.min.css" />
    <link rel="stylesheet" href="~/BulkyShWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.7/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />





</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BulkyShWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                        </li>

                        @if (User.IsInRole(SD.Roles.Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Mangament
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>

                                    <li><hr class="dropdown-divider"></li>
                                    
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">User Managment</a>
                                    </li>

                                </ul>
                            </li>

                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>


                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                    @await Component.InvokeAsync("ShoppingCart")
                                </a>
                            </li>
 
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifcations"></partial>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary *text-muted">
        <div class="container text-center">
            BulkyShWeb <i class="bi bi-watch"></i>
        </div>
    </footer>
    <script src="https://cdn.tiny.cloud/1/9eabbi0c36vxixf308qmlrxdfgyzw6m7v2r42pmlm217ugyd/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdn.datatables.net/2.1.7/js/dataTables.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkySh.Web/Views/Shared/_Notifcations.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
    toastr.success('@TempData["Success"]')
    </script>

}
@if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Error"]')
    </script>
}